<?php

namespace T2N\endiorite;

use T2N\endiorite\API\ClearLag;
use T2N\endiorite\API\CommandsAPI;
use T2N\endiorite\API\CustomBlockLoad;
use T2N\endiorite\API\CustomItemLoad;
use T2N\endiorite\API\EnderChestAPI;
use T2N\endiorite\API\EventsAPI;
use T2N\endiorite\API\HomeAPI;
use T2N\endiorite\API\RankAPI;
use T2N\endiorite\API\TasksLoad;
use T2N\endiorite\API\Utils;
use muqsit\invmenu\InvMenuHandler;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\Config;

class Main extends PluginBase {

    public static Main $instance;

    public Utils $utils;
    public ClearLag $clearLag;
    public EventsAPI $eventsAPI;
    public CustomBlockLoad $customBlockLoad;
    public CustomItemLoad $customItemLoad;
    public HomeAPI $homeAPI;
    public CommandsAPI $commandsAPI;
    public TasksLoad $tasksLoad;
    public EnderChestAPI $enderChestAPI;

    public Config $rankConfig;

    protected function onEnable(): void {
        self::$instance = $this;
        $this->utils = new Utils();
        $this->clearLag = new ClearLag();
        $this->eventsAPI = new EventsAPI();
        $this->customBlockLoad = new CustomBlockLoad();
        $this->customItemLoad = new CustomItemLoad();
        $this->homeAPI = new HomeAPI();
        $this->commandsAPI = new CommandsAPI();
        $this->tasksLoad = new TasksLoad();
        $this->enderChestAPI = new EnderChestAPI();

        $this->rankConfig = new Config($this->getDataFolder() . "rank.yml");

        $this->clearLag->init();

        @mkdir($this->getDataFolder() . "stats");
        $this->getServer()->getNetwork()->setName("§l§9Endiorite §fV3§r");

        if(!InvMenuHandler::isRegistered()) {
            InvMenuHandler::register($this);
        }

        parent::onEnable(); // TODO: Change the autogenerated stub
    }

}